In [1]:
a=10,20,30
type(a)

tuple

In [2]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
c=np.array([[1,2,3,4,5],[5,6,7,8,9]])
type(c)

numpy.ndarray

In [4]:
np.ndim(a)

1

In [5]:
np.ndim(c)

2

In [6]:
c

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [7]:
np.size(c)

10

In [8]:
np.shape(c)

(2, 5)

In [9]:
d=np.array([[[1,2,3],[7,8,9],[4,5,6]],[[11,12,13],[1,2,3],[4,5,6]]])
d

array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [ 1,  2,  3],
        [ 4,  5,  6]]])

In [10]:
np.shape(d)

(2, 3, 3)

In [11]:
s=np.arange(1,51)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
#s=np.arange(1,51,2)
#s

In [13]:
s1=np.arange(2,51,2)
s1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [14]:
s2=s.reshape(5,10)
s2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [15]:
s2.dtype

dtype('int64')

In [62]:
d5=s2[1:4,2:6]
d5

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [17]:
s3=s2.astype("float")
s3

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]])

In [18]:
s3.dtype

dtype('float64')

In [20]:
d2=np.linspace(1,10,5)
d2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
s3[2][5]

np.float64(26.0)

In [28]:
#vectorization function or loop
def fun(l):
    return l*10
l=[1,2,3,4,5]

f=list(map(fun,l))
f

[10, 20, 30, 40, 50]

In [30]:
la=np.array(l)
la*10

array([10, 20, 30, 40, 50])

In [38]:
b1=[1,2,3,4]
print(b1)

b2=[[5],[6],[7],[8]]
print(b2)

print(b1+b2)

[1, 2, 3, 4]
[[5], [6], [7], [8]]
[1, 2, 3, 4, [5], [6], [7], [8]]


In [39]:
a=np.array(b1)
b=np.array(b2)
print(a*b)

[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [40]:
np.dot(a,b)

array([70])

In [41]:
a@b

array([70])

In [42]:
np.sum(a)

np.int64(10)

In [43]:
np.min(a)

np.int64(1)

In [44]:
np.max(a)

np.int64(4)

In [45]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [46]:
np.std(a)

np.float64(1.118033988749895)

In [47]:
np.mean(a)

np.float64(2.5)

In [55]:
a=np.array([4,3,5,2,1,100]) #sort
np.mean(a)

np.float64(19.166666666666668)

In [56]:
np.median(a)

np.float64(3.5)

In [57]:
np.random.rand(4,4)

array([[0.19255308, 0.83856606, 0.07759587, 0.98804694],
       [0.30134438, 0.03590627, 0.56194696, 0.1353267 ],
       [0.97933386, 0.26464409, 0.59263947, 0.17210543],
       [0.86585365, 0.64571027, 0.13444444, 0.18142268]])

In [58]:
np.random.randint(1000,5000,5)

array([2037, 1830, 2014, 4872, 2401], dtype=int32)

In [61]:
np.random.normal(2,5,100) #mean, std, size

array([-5.73137337e+00,  2.95039244e+00,  3.48998304e+00,  1.93458547e+00,
       -8.81367328e-01,  1.01335063e+01, -3.37971267e-01, -6.97760645e-01,
        1.16685589e+00, -6.67802447e+00, -1.64306763e+00, -6.25094708e-03,
        4.53342634e+00,  6.26877776e+00,  5.72102163e+00, -4.99083662e-02,
        2.98996269e+00,  2.38481291e+00,  5.63840613e+00,  3.85058979e+00,
        3.01114014e+00,  9.52643932e+00, -5.11622719e+00, -5.70630974e+00,
        3.70704860e-01, -7.58278194e+00,  9.39053130e+00,  7.23175109e+00,
        4.85137296e+00,  1.51835878e+00, -6.68393800e-02, -4.51440843e+00,
        2.80952139e+00,  2.85835575e+00,  7.92289680e+00,  1.17111860e+00,
        1.85484825e+00, -3.03494141e+00, -2.77111603e+00, -2.82628118e-01,
        4.51743411e+00,  2.57967512e+00, -1.09981461e+01, -3.65030548e+00,
        8.97240558e+00,  2.00815324e+00,  9.47412218e-01,  1.96153566e+00,
        6.16978907e-01,  1.17980232e-01,  5.11599638e+00, -2.08999039e+00,
       -3.65668694e+00,  

In [63]:
#boolean filtering
print(d5>30)

[[False False False False]
 [False False False False]
 [ True  True  True  True]]


In [64]:
b2

[[5], [6], [7], [8]]

In [68]:
print(b.reshape(1,-1))

[[5 6 7 8]]


In [67]:
b

array([[5],
       [6],
       [7],
       [8]])

In [69]:
np.ndim(b)

2

In [70]:
c=b.reshape(1,-1)
c

array([[5, 6, 7, 8]])

In [71]:
np.ndim(c)

2

In [72]:
v=np.array([1,2,3,4,5])