In [1]:
a=10,20,30
type(a)

tuple

In [2]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
c=np.array([[1,2,3,4,5],[5,6,7,8,9]])
type(c)

numpy.ndarray

In [4]:
np.ndim(a)

1

In [5]:
np.ndim(c)

2

In [6]:
c

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [7]:
np.size(c)

10

In [8]:
np.shape(c)

(2, 5)

In [9]:
d=np.array([[[1,2,3],[7,8,9],[4,5,6]]])
d

array([[[1, 2, 3],
        [7, 8, 9],
        [4, 5, 6]]])

In [10]:
np.shape(d)

(1, 3, 3)

In [11]:
s=np.arange(1,51)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
#s=np.arange(1,51,2)
#s

In [13]:
s1=np.arange(2,51,2)
s1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [16]:
s2=s.reshape(5,10)
s2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [21]:
s2.dtype

dtype('int64')

In [22]:
s2[1:4,2:6]

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [24]:
s3=s2.astype("float")
s3

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]])

In [25]:
s3.dtype

dtype('float64')